from django.conf.urls import url
import labbd.views

urlpatterns = [
    url(r'^$', labbd.views.show),
    url(r'^orders/$', labbd.views.show_orders),
    url(r'^orders/add/$', labbd.views.show_add_order),
    url(r'^orders/add/update/$', labbd.views.add_order),
    url(r'^orders/(?P<order_id>\d+)/$', labbd.views.show_order),
    url(r'^orders/(?P<order_id>\d+)/delete/$', labbd.views.delete_order),
    url(r'^orders/(?P<order_id>\d+)/edit/$', labbd.views.show_edit_order),
    url(r'^orders/(?P<order_id>\d+)/edit/update/$', labbd.views.edit_order),
    url(r'^clients/$', labbd.views.show_clients),
    url(r'^clients/(?P<client_id>\d+)/$', labbd.views.show_client),
    url(r'^clients/(?P<client_id>\d+)/update/$', labbd.views.edit_client),
    url(r'^clients/(?P<client_id>\d+)/delete/$', labbd.views.delete_client),
    url(r'^clients/add/$', labbd.views.show_add_client),
    url(r'^clients/add/update/$', labbd.views.add_client),
    url(r'^hairstyles/$', labbd.views.show_hairstyles),
    url(r'^hairstyles/(?P<hairstyle_id>\d+)/$', labbd.views.show_hairstyle),
    url(r'^hairstyles/(?P<hairstyle_id>\d+)/update/$', labbd.views.edit_hairstyle),
    url(r'^hairstyles/(?P<hairstyle_id>\d+)/delete/$', labbd.views.delete_hairstyle),
    url(r'^hairstyles/add/$', labbd.views.show_add_hairstyle),
    url(r'^hairstyles/add/update/$', labbd.views.add_hairstyle),
    url(r'^masters/$', labbd.views.show_masters),
    url(r'^masters/(?P<master_id>\d+)/$', labbd.views.show_master),
    url(r'^masters/(?P<master_id>\d+)/update/$', labbd.views.edit_master),
    url(r'^masters/(?P<master_id>\d+)/delete/$', labbd.views.delete_master),
    url(r'^masters/add/$', labbd.views.show_add_master),
    url(r'^masters/add/update/$', labbd.views.add_master),
    url(r'^queries/$', labbd.views.show_queries),
    url(r'^queries/(?P<query_id>\d+)/$', labbd.views.show_query),
    url(r'^queries/1/show/$', labbd.views.show_exec_query01),
    url(r'^queries/2/show/$', labbd.views.show_exec_query02),
    url(r'^queries/3/show/$', labbd.views.show_exec_query03),
    url(r'^queries/4/show/$', labbd.views.show_exec_query04),
    url(r'^queries/5/show/$', labbd.views.show_exec_query05),
    url(r'^queries/6/show/$', labbd.views.show_exec_query06),
    url(r'^queries/7/show/$', labbd.views.show_exec_query07),
]
